# Generated by Django 3.2.3 on 2021-06-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_car_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
