# Generated by Django 3.2.3 on 2021-06-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_car_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='img',
        ),
    ]
